name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Checkout, build and deploy to container registry
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build . --tag registry.digitalocean.com/dexllc/website:latest
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/dexllc/website:latest
      
