name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Checkout, build and deploy to container registry
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build . --tag registry.digitalocean.com/dexllc/website
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/dexllc/website

    - name: Redeploy app
      run: doctl apps create-deployment a61a8b18-ace8-4c08-b822-9d139c750da7 --force-rebuild true
      
